"""Collector authentication.

The collector authenticates with COLLECTOR_API_KEY, sent either as:
    Authorization: Bearer <key>
or:
    x-collector-key: <key>

This key is NOT a Supabase key and NOT a BC.GAME credential.
It is generated by us and stored server-side only.
"""
from typing import Optional

from fastapi import Header, HTTPException, status

from .config import COLLECTOR_API_KEY


async def require_collector_key(
    authorization: Optional[str] = Header(None),
    x_collector_key: Optional[str] = Header(None),
) -> str:
    if not COLLECTOR_API_KEY:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="COLLECTOR_API_KEY not configured on server",
        )

    provided: Optional[str] = None
    if authorization and authorization.lower().startswith("bearer "):
        provided = authorization[7:].strip()
    elif x_collector_key:
        provided = x_collector_key.strip()

    if not provided or provided != COLLECTOR_API_KEY:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid collector credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )
    return "COLLECTOR_API_KEY"
